#!/bin/sh
HERE="$(readlink -f "$(dirname "$0")")"
#HERE="$(dirname "$(readlink -f "$0")")"

# make srcpkg2git prefer the bundled squashfs
export PATH="$HERE"/usr/bin:"$PATH"

#exec "$HERE"/usr/bin/srcpkg2git "$@"
exec srcpkg2git "$@"
